---
title: "20160321Demo2"
author: "David Chiu"
date: "2016年3月21日"
output: html_document
---

```{r}

x =c(0, 0, 1, 1, 1, 1)
y =c(1, 0, 1, 1, 0, 1)

#euclidean
dist(rbind(x,y), method ="euclidean")
sqrt(sum((x-y)^2))
dist(rbind(x,y), method ="minkowski", p=2)

#city block
dist(rbind(x,y), method ="manhattan")
sum(abs(x-y))
dist(rbind(x,y), method ="minkowski", p=1)

```

```{r}
# customer clustering
customer=read.csv('customer.csv',header=TRUE)
head(customer)
str(customer)
customer =scale(customer[,-1])
hc=hclust(dist(customer, method="euclidean"), method="ward.D2")
plot(hc, hang =-0.01, cex=0.7)

hc3 =hclust(dist(customer), method="single")
plot(hc3, hang =-0.01, cex=0.7)


library(cluster)
#?diana
dv =diana(customer, metric ="euclidean")
summary(dv)
plot(dv)

# iris clustering
data(iris)
hc2=hclust(dist(iris[,-5], method="euclidean"), method="ward.D2")
plot(hc2, hang =-0.01, cex=0.7)



```

```{r}
fit =cutree(hc, k =4)
table(fit)
plot(hc)
rect.hclust(hc, k =4, border="red")
rect.hclust(hc, k =3, border="blue")

```

```{r}
str(customer)
set.seed(22)
fit =kmeans(customer, 4)
barplot(t(fit$centers), beside =TRUE,xlab="cluster", ylab="value")

plot(customer, col=fit$cluster)

```

```{r}
set.seed(22)
fit =kmeans(iris[,-5], 3)
barplot(t(fit$centers), beside =TRUE,xlab="cluster", ylab="value")
plot(iris, col=fit$cluster)

plot(iris$Sepal.Length, iris$Petal.Width, col=fit$cluster)

```
```{r}
set.seed(22)
km =kmeans(customer, 4)
kms=silhouette(km$cluster,dist(customer))
summary(kms)
plot(kms)

```

```{r}
nk=2:10
set.seed(22)
WSS =sapply(nk, function(k){
  kmeans(customer, centers=k)$tot.withinss
  })

WSS
plot(nk, WSS, type="l", xlab="number of k", ylab="within sum of squares")
```

```{r}
#install.packages("fpc")
library(fpc)
SW =sapply(nk, function(k){cluster.stats(dist(customer), kmeans(customer, centers=k)$cluster)$avg.silwidth
  })
plot(nk, SW, type="l", xlab="number of clusers", ylab="average silhouette width")
```

```{r}
single_c=hclust(dist(customer), method="single")
hc_single=cutree(single_c, k =4)

complete_c=hclust(dist(customer), method="complete")
hc_complete=cutree(complete_c, k =4)

set.seed(22)
km =kmeans(customer, 4)

cs=cluster.stats(dist(customer),km$cluster)
cs[c("within.cluster.ss","avg.silwidth")]

sapply(
  list(kmeans=km$cluster, 
       hc_single=hc_single, 
       hc_complete=hc_complete), function(c)cluster.stats(dist(customer), c)[c("within.cluster.ss","avg.silwidth")])



```

```{r}
data(iris)
data<-iris[,-5]
class<-iris[,5]

results <-kmeans(data,3)
results
results$size
results$cluster

table(class,results$cluster)
par(mfrow=c(2, 2))
plot(data$Petal.Length, data$Petal.Width,col=results$cluster)
plot(data$Petal.Length, data$Petal.Width,col=class)
plot(data$Sepal.Length, data$Sepal.Width,col=results$cluster)
plot(data$Sepal.Length, data$Sepal.Width,col=class)
```


