---
title: "20160314Tutorial"
author: "David Chiu"
date: "2016年3月14日"
output: html_document
---

# Heading1
## Heading2
###  Heading3

### item
- list1
- list2
- list3
    1. qoo
    2. oop
    3. ooc
    
```
this is a code block
```

```{r}
a = 3
b = 2
a + b

```

```{r echo=FALSE}
#echo =FALSE
a + b

```

```{r eval=FALSE}
#eval =FALSE
a + b

```

```{r include=FALSE}
#include =FALSE
a + b
```


## TW2330 Analysis
```{r include=FALSE}
#download.file("http://real-chart.finance.yahoo.com/table.csv?s=2330.TW&d=2&e=14&f=2016&g=d&a=0&b=4&c=2000&ignore=.csv", "2330.csv")
```

```{r}

tw2330 = read.csv("2330.csv", header=TRUE)
max(tw2330$Close)
min(tw2330$Close)
summary(tw2330$Close)
hist(tw2330$Close)
boxplot(tw2330$Close)

lower_bound = max(min(tw2330$Close), median(tw2330$Close) - 1.5 * IQR(tw2330$Close))
upper_bound = min(max(tw2330$Close), median(tw2330$Close) + 1.5 * IQR(tw2330$Close))

class(tw2330)
str(tw2330)
tw2330$Date = as.Date(tw2330$Date)
str(tw2330)
plot(tw2330$Date, tw2330$Close)
tw2330$tf = tw2330$Close - tw2330$Open > 0
table(tw2330$tf)

```

### Learning map
- http://scikit-learn.org/stable/_static/ml_map.png
- http://people.revoledu.com/kardi/tutorial/DecisionTree/how-to-measure-impurity.htm
- http://images.slideplayer.com/16/5055084/slides/slide_20.jpg

## Iris Classfication with rpart
```
install.packages("rpart")

```
```{r}
library(rpart)
data(iris)
head(iris)

fit = rpart(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, data = iris)
plot(fit, margin=0.1)
text(fit)
plot(iris$Petal.Length, iris$Petal.Width, col=iris$Species)
abline(v = 2.45, col ="blue")
abline(h = 1.75, col ="orange")
predict_one = predict(fit, iris[1,])

predict_all = predict(fit, iris, type="class")
table(iris$Species, predict_all)
```


```{r}
#install.packages("party")
library(party)
data(iris)
head(iris)

fit2 = ctree(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, data = iris)
plot(fit, margin=0.1)

plot(iris$Petal.Length, iris$Petal.Width, col=iris$Species)
abline(v = 1.9, col ="blue")
abline(h = 1.7, col ="orange")
abline(v = 4.8, col ="red")
predict_all2 = predict(fit2, iris)
table(iris$Species, predict_all2)
```


```{r}
#install.packages("e1071")
library(e1071)
data(iris)
head(iris)

fit3 = svm(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, data = iris)

predict_all3 = predict(fit3, iris)
table(iris$Species, predict_all3)
```


```{r}
library(e1071)

fit4 = naiveBayes(Species ~ ., data = iris)

predict_all4 = predict(fit4, iris)
table(iris$Species, predict_all4)
```

### Churn analysis
```{r}
#install.packages("C50")
library(C50)

data(churn)
str(churnTrain)
names(churnTrain) %in% c("state", "area_code", "account_length")
! names(churnTrain) %in% c("state", "area_code", "account_length")
churnTrain=churnTrain[,!names(churnTrain)%in%c("state", "area_code", "account_length")]

set.seed(2)
ind<-sample(2, nrow(churnTrain), replace=TRUE, prob=c(0.7, 0.3))
trainset=churnTrain[ind==1,]
testset=churnTrain[ind==2,]


table(sample(2, replace=TRUE,100))
table(sample(2, replace=TRUE,100, prob=c(0.7,0.3)))

a = c(1,2,3,4,5,6,7,8,9)
ind = c(1,0,1,0,1,0,1,0,1)
ind == 1
a[ind == 1]
a[ind == 0]

```

### rpart analysis
```{r}
churn.rp<-rpart(churn ~., data=trainset)
plot(churn.rp, margin=0.1)
text(churn.rp, all=TRUE, use.n=TRUE)
```

### Prune
```{r}
min(churn.rp$cptable[,"xerror"])
which.min(churn.rp$cptable[,"xerror"])
churn.cp = churn.rp$cptable[8, "CP"]
prune.tree=prune(churn.rp, cp=churn.cp)
plot(prune.tree, margin=0.1)
text(prune.tree, all=TRUE, use.n=TRUE)


predictions <-predict(churn.rp, testset, type="class")
table(testset$churn, predictions)
```

### ctree analysis
```{r}
churn.rp<-ctree(churn ~., data=trainset)
plot(churn.rp, margin=0.1)
```


### caret cross- validation
```{r}
#install.packages("caret")
library(caret)
control=trainControl(method="repeatedcv", number=10, repeats=3)
model =train(churn~., data=trainset, method="rpart", preProcess="scale", trControl=control)
model
predict(model, testset)

```

```{r}
#install.packages("rminer")
library(rminer)
model=fit(churn~.,trainset,model="svm")
VariableImportance=Importance(model,trainset,method="sensv")

L=list(runs=1,sen=t(VariableImportance$imp),sresponses=VariableImportance$sresponses)
mgraph(L,graph="IMP",leg=names(trainset),col="gray",Grid=10)
```
